export const GET_ACTORS_REQUEST = "GET_ACTORS_REQUEST";
export const GET_ACTORS_SUCCESS = "GET_ACTORS_SUCCESS";
export const GET_ACTORS_FAIL = "GET_ACTORS_FAIL";

export const GET_ACTOR_REQUEST = "GET_ACTOR_REQUEST";
export const GET_ACTOR_SUCCESS = "GET_ACTOR_SUCCESS";
export const GET_ACTOR_FAIL = "GET_ACTOR_FAIL";