export const GET_CHARACTERS_REQUEST = "GET_CHARACTERS_REQUEST";
export const GET_CHARACTERS_SUCCESS = "GET_CHARACTERS_SUCCESS";
export const GET_CHARACTERS_FAIL = "GET_CHARACTERS_FAIL";

export const GET_CHARACTER_REQUEST = "GET_CHARACTER_REQUEST";
export const GET_CHARACTER_SUCCESS = "GET_CHARACTER_SUCCESS";
export const GET_CHARACTER_FAIL = "GET_CHARACTER_FAIL";
