export const GET_FILMS_REQUEST = "GET_FILMS_REQUEST";
export const GET_FILMS_SUCCESS = "GET_FILMS_SUCCESS";
export const GET_FILMS_FAIL = "GET_FILMS_FAIL";

export const GET_FILM_REQUEST = "GET_FILM_REQUEST";
export const GET_FILM_SUCCESS = "GET_FILM_SUCCESS";
export const GET_FILM_FAIL = "GET_FILM_FAIL";