export const GET_PLANETS_REQUEST = "GET_PLANETS_REQUEST";
export const GET_PLANETS_SUCCESS = "GET_PLANETS_SUCCESS";
export const GET_PLANETS_FAIL = "GET_PLANETS_FAIL";

export const GET_PLANET_REQUEST = "GET_PLANET_REQUEST";
export const GET_PLANET_SUCCESS = "GET_PLANET_SUCCESS";
export const GET_PLANET_FAIL = "GET_PLANET_FAIL";