export const GET_SPECIES_REQUEST = "GET_SPECIES_REQUEST";
export const GET_SPECIES_SUCCESS = "GET_SPECIES_SUCCESS";
export const GET_SPECIES_FAIL = "GET_SPECIES_FAIL";

export const GET_SPECIE_REQUEST = "GET_SPECIE_REQUEST";
export const GET_SPECIE_SUCCESS = "GET_SPECIE_SUCCESS";
export const GET_SPECIE_FAIL = "GET_SPECIE_FAIL";