export const GET_STARSHIPS_REQUEST = "GET_STARSHIPS_REQUEST";
export const GET_STARSHIPS_SUCCESS = "GET_STARSHIPS_SUCCESS";
export const GET_STARSHIPS_FAIL = "GET_STARSHIPS_FAIL";

export const GET_STARSHIP_REQUEST = "GET_STARSHIP_REQUEST";
export const GET_STARSHIP_SUCCESS = "GET_STARSHIP_SUCCESS";
export const GET_STARSHIP_FAIL = "GET_STARSHIP_FAIL";